name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x]
        cmd: [lint, "fbjs:build", "fbjs:test", "fbjs:flow", "preset:test", "signedsource:test"]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run ${{ matrix.cmd }}
      run: yarn run ${{ matrix.cmd }}
